// mutation-types.js
export const SOME_MUTATION = 'SOME_MUTATION'
export const INCREMENT = 'INCREMENT'
export const ERROR = 'ERROR'
export const SUCCESS = 'SUCCESS'
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const ADD_TO_CART = 'ADD_TO_CART'
export const SHOW_CART = 'SHOW_CART'
export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS'
export const SET_PRODUCTS = 'SET_PRODUCTS'
